name: Build Windows
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - precision: single
            arch: x86_32
            opencl_arch: Win32
          - precision: single
            arch: x86_64
            opencl_arch: x64
          - precision: double
            arch: x86_32
            opencl_arch: Win32
          - precision: double
            arch: x86_64
            opencl_arch: x64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: 🔗 GDExtension Build
        uses: godot/godot-cpp-template/.github/actions/build
        with:
          platform: windows
          arch: ${{ matrix.arch }}
          godot-cpp-location: godot-cpp
          float-precision: ${{ matrix.precision }}
          build-target-type: template_release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Godot_Speech
          path: |
            ${{ github.workspace }}/bin/**/*.dll
            ${{ github.workspace }}/bin/samples/**
            ${{ github.workspace }}/bin/addons/godot_speech/godot_speech.gdextension
          if-no-files-found: error
          compression-level: 9
